Client js feat 2.0 (#301)
* Uodate crate casper-contract

* Cargo test stable

* small change

* Backport message_topic fix from https://github.com/casper-ecosystem/cep18/issues/162

* Add some upgrade test with events change

* // typo

* Clippy

* First commit

* stash

* stash

* stash

* Clean init_events

* stash

* stash

* stash

* stash + tests

* stash test

* stash tests

* Fix tests

* Upgrade tests

* typo

* test e2e events

* Add some usage tests

* Clean up

* Add e2e tests

* Update readme

* Update deps + tests + CI + Readme

* Remove logging

* Small change

* Move toolchain again

* Update toolchain

* Unused file

* Remove file

* Condor > 2.0

* npm audit

* Test CI/CD

* Revert

* Test CI/CD

* Revert

* Test CI

* Test CI

* Revert + add fake ubuntu 20.04/22.04 step

diff --git a/.github/workflows/ci-cep-78-client.yml b/.github/workflows/ci-cep-78-client.yml
--- a/.github/workflows/ci-cep-78-client.yml
+++ b/.github/workflows/ci-cep-78-client.yml
@@ -1,64 +1,119 @@
-# name: ci-casper-cep78-js-client
+name: ci-casper-cep78-js-client
 
-# on:
-#   push:
-#     branches:
-#       - "dev"
-#       - "feat-*"
-#       - "release-*"
+on:
+  push:
+    branches: [dev, feat-*, release-*]
 
-#   pull_request:
-#     branches:
-#       - "dev"
-#       - "feat-*"
-#       - "release-*"
+  pull_request:
+    branches: [dev, feat-*, release-*]
 
-# jobs:
-#   client-build:
-#     strategy:
-#       fail-fast: false
-#       matrix:
-#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
-#         node-version: [18.x]
-#         os: [ubuntu-20.04, ubuntu-22.04]
-#     runs-on: ${{ matrix.os }}
+jobs:
+  ci-js-client:
+    strategy:
+      matrix:
+        os: [ubuntu-latest]
+        node-version: [22.x]
+    runs-on: ${{ matrix.os }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          profile: minimal
+          components: rustfmt, clippy
+      - run: sudo apt update && sudo apt install -y build-essential wabt
+      - uses: Swatinem/rust-cache@v2
+      - run: make prepare
+      - run: make setup-test
 
-#     steps:
-#       - name: Checkout
-#         uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
+      - name: Start Casper NCTL Service
+        run: |
+          docker run -d \
+            --name casper-nctl \
+            -p 11101-11105:11101-11105 \
+            -p 14101-14105:14101-14105 \
+            -p 18101-18105:18101-18105 \
+            -p 25101-25105:25101-25105 \
+            -p 28101-28105:28101-28105 \
+            -v $PWD/assets/users:/app/casper-nctl/assets/net-1/users/ \
+            -v $PWD/assets/faucet:/app/casper-nctl/assets/net-1/faucet/ \
+            gregoshop/casper-nctl:2.0
 
-#       - uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c #v1.4.0
+      - name: Wait for the service to be ready
+        run: |
+          echo "Waiting for the service to be ready on port 11101..."
+          for i in {1..30}; do # wait for up to 30 seconds
+            if nc -z localhost 11101; then
+              echo "Service is up!"
+              echo "Wait 45s for nctl to boot and create keys"
+              sleep 45  # - name: wait for up to 45 seconds for an era like
+              break
+            fi
+            echo "Waiting..."
+            sleep 1
+          done
 
-#       - name: Install dependencies
-#         run: sudo apt update && sudo apt install -y build-essential wabt
+          # Check if the service is still not ready after 30 seconds
+          if ! nc -z localhost 11101; then
+            echo "Service did not start in time!"
+            exit 1
+          fi
 
-#       - name: Setup
-#         run: make prepare
+          echo "Waiting for the service to be ready on http://127.0.0.1:18101/events..."
 
-#       - name: Prepare WASMs
-#         run: make setup-test
+          for i in {1..30}; do  # Wait for up to 30 seconds
+            if curl --silent --max-time 2 http://127.0.0.1:18101/events | grep -q "ApiVersion"; then
+              echo "Service is up!"
+              break
+            fi
+            echo "Waiting..."
+            sleep 1
+          done
 
-#       - name: Use Node.js ${{ matrix.node-version }}
-#         uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
-#         with:
-#           node-version: ${{ matrix.node-version }}
+          # Final check after timeout
+          if ! curl --silent --max-time 2 http://127.0.0.1:18101/events | grep -q "ApiVersion"; then
+            echo "Service did not start in time!"
+            exit 1
+          fi
 
-#       - name: Install
-#         working-directory: ./client-js
-#         run: npm install
+      # WARNING: These accounts, and their private keys, are now publicly known.
+      # Any funds sent to them on Mainnet or any other live network WILL BE LOST.
+      - name: Set environment variables
+        run: |
+          echo "PRIVATE_KEY_FAUCET=$(sed -n '2p' ./assets/faucet/secret_key.pem)" >> $GITHUB_ENV
+          echo "PRIVATE_KEY_USER_1=$(sed -n '2p' ./assets/users/user-1/secret_key.pem)" >> $GITHUB_ENV
+          echo "PRIVATE_KEY_USER_2=$(sed -n '2p' ./assets/users/user-2/secret_key.pem)" >> $GITHUB_ENV
 
-#       - name: Copy & convert WASMs
-#         working-directory: ./client-js
-#         run: npm run wasms:convert
+      - name: Print GITHUB_ENV
+        run: |
+          echo "Contents of GITHUB_ENV:"
+          cat $GITHUB_ENV
 
-#       - name: Audits
-#         working-directory: ./client-js
-#         run: npm audit --omit=dev
+      - name: Use Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          registry-url: 'https://registry.npmjs.org'
 
-#       - name: Lints
-#         working-directory: ./client-js
-#         run: npm run lint
+      - name: Audit
+        working-directory: client-js
+        run: npm audit
 
-#       - name: Test
-#         working-directory: ./client-js
-#         run: npm test
+      - name: Install Dependencies
+        working-directory: client-js
+        run: npm install
+
+      - name: Generate WASMS
+        working-directory: client-js
+        run: npm run generate:wasm
+
+      - name: Build Project
+        working-directory: client-js
+        run: npm run build
+
+      - name: Run Unit/E2E Tests
+        working-directory: client-js
+        run: |
+          set -e  # Fail fast if any command fails
+          npm run test
